Mason edited 4 pages
gsbdarc/rcpedia_mockup pull request #34
Opened 2024-10-16 23:36 UTC by mpj2104

Mason edited the following pages:

- `_policies/acknowledgements/`
- `_policies/security/`
- `blog/2023/05/16/sec-filings/`
- `blog/2023/09/18/transferring-files-from-the-yens-to-google-drive-using-rclone/`

2024-10-17 14:07 UTC, natalya-patrikeeva requested changes
I left comments on some code blocks - we are adding titles, removing $, disable copy if it's output etc. I didn't mark all of them though.

2024-10-17 14:07 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-05-16-EDGARmirror.md
>  ```
I would maybe add a Summary to say something about the whole page. It ends abruptly.

2024-10-17 14:07 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-09-18-rclone.md
> +# Transferring files from the Yens to Google Drive using `rclone`
Can we shorten the title to fit into one line? Maybe something like "rclone files from Yens to Google drive"

2024-10-17 14:07 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-09-18-rclone.md
> +<div class="last-updated">Last updated: 2024-09-30</div>
don't need this

2024-10-17 14:07 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-09-18-rclone.md
>  ```bash
add title, remove $ so readers can copy

2024-10-17 14:07 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-09-18-rclone.md
>  $ ml rclone
only show output, disable copy and add title that is the "Terminal Output"

2024-10-17 22:07 UTC, mpj2104 commented on docs/blog/posts/2023-05-16-EDGARmirror.md
>  ```
hmmm, i never explicitly defined a "copy button", it just shows up when the page gets rendered

2024-10-18 00:44 UTC, natalya-patrikeeva approved these changes
Besides the emoji, looks good to me. We can pretty up rclone page later. I might have nit picky styling things

2024-10-18 00:44 UTC, natalya-patrikeeva commented on docs/blog/.authors.yml
> +    description: 🦄 Lead Research Analytics Scientist @DARC GSB Team  # Author description
Can Amy get a different emoji lol

2024-10-18 00:44 UTC, natalya-patrikeeva commented on docs/blog/.authors.yml
> +    description: 🦄 Lead Research Analytics Scientist @DARC GSB Team  # Author description
In fact, we all should get an emoji

2024-10-18 05:04 UTC, mpj2104 commented on docs/blog/.authors.yml
> +    description: 🦄 Lead Research Analytics Scientist @DARC GSB Team  # Author description
oopsie, fixed now

2024-10-18 05:05 UTC, merged