adding julia on slurm
gsbdarc/rcpedia_mockup pull request #55
Opened 2024-11-19 22:18 UTC by natalya-patrikeeva

adding julia on slurm and deleting old julia job array page as it is absorbed into the combined slurm array page

2024-11-19 23:18 UTC, mpj2104 requested changes
Main question is about Yen-Slurm vs Yen Slurm

2024-11-19 23:18 UTC, mpj2104 commented on docs/_user_guide/julia-slurm.md
> +# Running Julia on Yen-Slurm
When I edited the Slurm page, I changed all Yen-Slurm to Yen Slurm. Not sure which is better for consistency?

2024-11-19 23:18 UTC, mpj2104 commented on docs/_user_guide/julia-slurm.md
> +## Single-threaded Julia on Yen-Slurm
same question here with Yen-Slurm

2024-11-19 23:18 UTC, mpj2104 commented on docs/_user_guide/julia-slurm.md
> +Similar to running Julia interactively, we will load Julia module but run the script using Slurm scheduler so that the script is executed on the Yen-Slurm nodes.
The only time I used the hyphen, was referring to `yen-slurm`. I don't feel particularly strongly about the notation, so maybe we choose one and stick with it.

2024-11-19 23:18 UTC, mpj2104 commented on docs/_user_guide/julia-slurm.md
> +## Multi-threaded Julia on Yen-Slurm
just flagging Yen-Slurm again

2024-11-19 23:18 UTC, mpj2104 commented on docs/_user_guide/julia-slurm.md
> +julia hello.jl
Add an example `hello.jl` script somewhere?

2024-11-20 21:43 UTC, natalya-patrikeeva commented
i'll cancel this PR since we are combining all languages into one slurm page

2024-11-20 21:43 UTC, closed without merging